services:
  cityfix-ui-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cityfix-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8087
    networks:
      - frontend-dev-network
    restart: unless-stopped

networks:
  frontend-dev-network:
    driver: bridge
    name: frontend-dev-network
